version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: booking-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Asdf1474"
      POSTGRES_DB: booking_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:asdf1474@db:5432/booking-management"
  #     JWT_SECRET: "Asdf1474!"
  #   depends_on:
  #     - db:
  #         condition: service_healthy

volumes:
  postgres_data: